server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
  datasource:

    url: jdbc:h2:~/testUserDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
  application:
    name: rds-example

#spring:
#  datasource:
#    url: jdbc:h2:mem:testUser
#    username: sa
#    password: 1234
#  h2:
#    console:
#      enabled: true
#  application:
#    name: rds-example

