
spring:

  application:
    name: first-sample
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false

  datasource:
    username: training
    password: 1234
    url: jdbc:mysql://localhost:3306/training?serverTimezone=UTC
